version: '3'

networks:
  blog-net:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - db
    container_name: laravel-cont
    networks:
      - blog-net

  db:
    image: mysql/mysql-server:5.7
    container_name: mysql-cont
    volumes:
      - /var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=123
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - blog-net